# Generated by Django 6.0.2 on 2026-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydestination',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
