# Generated by Django 6.0.2 on 2026-02-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_studydestination_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancyteammember',
            old_name='role',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='consultancyteammember',
            name='is_chairman',
        ),
        migrations.RemoveField(
            model_name='consultancyteammember',
            name='social_links',
        ),
        migrations.AddField(
            model_name='consultancyteammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='consultancyteammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultancyteammember',
            name='role_type',
            field=models.CharField(choices=[('leader', 'Leadership'), ('counsellor', 'Counsellor'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='consultancyteammember',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultancyteammember',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
